version: "3.7"

services:
  mariadb:
    build: ./mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - ./Data/mysql:/var/lib/mysql
    expose:
      - "3306"
    env_file:
      - ./.env
    networks:
      - inception
    restart: on-failure

# volumes:
#   mdb:
#     name: mdb
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: bind
#       device: ./Data/mysql

networks:
  inception:
    driver: bridge

