version: "3.7"

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - mdb:/var/lib/mysql
    expose:
      - "3306"
    env_file:
      - ./.env
    networks:
      - inception
    restart: on-failure
    secrets:
      - root_pass
      - sql_usr
      - sql_pass
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/root_pass
      - MYSQL_USER_FILE=/run/secrets/sql_usr
      - MYSQL_PASSWORD_FILE=/run/secrets/sql_pass
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure
    secrets:
      - sql_usr
      - sql_pass
      - wp_usr
      - wp_pass
      - wp_email
      - wp_admin
      - wp_admin_pass
      - wp_admin_email
    environment:
      - MYSQL_USER_FILE=/run/secrets/sql_usr
      - MYSQL_PASSWORD_FILE=/run/secrets/sql_pass
      - WP_USR_FILE=/run/secrets/wp_usr
      - WP_PWD_FILE=/run/secrets/wp_pass
      - WP_EMAIL_FILE=/run/secrets/wp_email
      - WP_ADMIN_USER_FILE=/run/secrets/wp_admin
      - WP_ADMIN_PWD_FILE=/run/secrets/wp_admin_pass
      - WP_ADMIN_EMAIL_FILE=/run/secrets/wp_admin_email
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:42
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure

volumes:
  mdb:
    name: mdb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rchavez/data/mysql
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rchavez/data/wordpress

networks:
  inception:
    driver: bridge

secrets:
  root_pass:
    file: ./secrets/root_pass
  sql_usr:
    file: ./secrets/sql_usr
  sql_pass:
    file: ./secrets/sql_pass
  wp_usr:
    file: ./secrets/wp_usr
  wp_pass:
    file: ./secrets/wp_pass
  wp_email:
    file: ./secrets/wp_email
  wp_admin:
    file: ./secrets/wp_admin
  wp_admin_pass:
    file: ./secrets/wp_admin_pass
  wp_admin_email:
    file: ./secrets/wp_admin_email