version: "3.7"

volumes:
  mdb:
    name: mdb
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: ./Data/mysql

networks:
  inception:
    driver: bridge

services:
  mariadb:
    build: ./mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - mdb:/var/lib/mysql
    expose:
      - "3306"
    env_file:
      - ./.env
    networks:
      - inception
    restart: always

  