version: "3.7"

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - mdb:/var/lib/mysql
    expose:
      - "3306"
    env_file:
      - ./.env
    networks:
      - inception
    restart: on-failure

volumes:
  mdb:
    name: mdb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/rchavez/Desktop/Inception/srcs/Data/mysql

networks:
  inception:
    driver: bridge

