version: "3.7"

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - mdb:/var/lib/mysql
    expose:
      - "3306"
    env_file:
      - ./.env
    networks:
      - inception
    restart: on-failure
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:42
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure

volumes:
  mdb:
    name: mdb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/rchavez/Desktop/Inception/srcs/Data/mysql
      # device: /Users/rodrigo/Desktop/Inception/srcs/Data/mysql
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/rchavez/Desktop/Inception/srcs/Data/wordpress
      # device: /Users/rodrigo/Desktop/Inception/srcs/Data/wordpress

networks:
  inception:
    driver: bridge

